apiVersion: apps/v1
kind: Deployment
metadata:
  name: vikareta-backend
  namespace: vikareta
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vikareta-backend
  template:
    metadata:
      labels:
        app: vikareta-backend
    spec:
      containers:
      - name: vikareta-backend
        image: ghcr.io/aryannkumar/vikareta-backend:main
        ports:
        - containerPort: 5001
        envFrom:
        - configMapRef:
            name: backend-config
        env:
        - name: PORT
          value: "5001"
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 5
